version: 0.2

phases:
  install:
    commands:
      - echo Installing zip...
      - apt-get update
      - apt-get install -y zip
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - NODE_ENV=development npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Node.js code
      - NODE_ENV=production npm run build
      - zip -r -x=*node_modules* dist.zip ./
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
